In [2]:
import numpy as np

## Creating an array

In [3]:
a = np.array([1,2,3,5,4])

In [5]:
a, type(a)

(array([1, 2, 3, 5, 4]), numpy.ndarray)

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = np.full(10,9)
a

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [25]:
m = np.ones((3,3), dtype=np.int32)
m, m.dtype

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 dtype('int32'))

### Random number generation

In [11]:
a = np.random.rand(10)
a

array([0.72864717, 0.36443928, 0.30607028, 0.7336018 , 0.71660245,
       0.62216248, 0.42444182, 0.57517163, 0.15596589, 0.73818104])

In [12]:
a = np.random.randint(1,100,10)
a

array([95, 34,  6, 14, 31, 88, 42, 89, 15, 39])

In [13]:
m = np.random.randint(1,100,(5,5))
m

array([[26,  8, 36, 10, 54],
       [14, 42, 67, 72, 64],
       [22, 63, 56, 94, 60],
       [37, 41,  7, 12, 19],
       [11, 67, 84, 68,  4]])

In [17]:
a = np.linspace(1,10,5, retstep=True)
a

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [18]:
a = np.array('Python')
a

array('Python', dtype='<U6')

In [19]:
a.size

1

In [20]:
l = list('Python')
l

['P', 'y', 't', 'h', 'o', 'n']

In [21]:
a = np.array(list('Python'))
a

array(['P', 'y', 't', 'h', 'o', 'n'], dtype='<U1')

#### Data Type

In [23]:
a = np.array( [1,2,3])
a, a.dtype

(array([1, 2, 3]), dtype('int32'))

### Attributes of ndarray

In [29]:
a = np.full((3,3),3)
print(a.size)
print(a.dtype)
print(a.shape)
print(a.ndim)

9
int32
(3, 3)
2


## Indexing and Slicing

In [32]:
a = np.arange(1,11)

In [33]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
a[0], a[-1]

(1, 10)

In [37]:
a[0:5]

array([1, 2, 3, 4, 5])

In [38]:
a[4:6]

array([5, 6])

In [41]:
a[-1:-4:-1]

array([10,  9,  8])

In [42]:
a[-3:]

array([ 8,  9, 10])

In [44]:
a[:3]

array([1, 2, 3])

In [48]:
a = np.arange(1,26).reshape((5,5))

In [49]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
a[4,3], a[-1,-1]

(24, 25)

In [53]:
a[1,:]

array([ 6,  7,  8,  9, 10])

In [54]:
a[:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [55]:
a[:, -1]

array([ 5, 10, 15, 20, 25])

In [57]:
# last 2 row and 2 cols
a[-2:,-2:]

array([[19, 20],
       [24, 25]])

In [58]:
a[3:,3:]

array([[19, 20],
       [24, 25]])

In [59]:
for n in a:
    print(n)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
[21 22 23 24 25]
