In [1]:
import numpy as np

## Creating an array

In [3]:
a = np.array([1,2,3,5,4])

In [5]:
a, type(a)

(array([1, 2, 3, 5, 4]), numpy.ndarray)

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = np.full(10,9)
a

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [25]:
m = np.ones((3,3), dtype=np.int32)
m, m.dtype

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 dtype('int32'))

### Random number generation

In [11]:
a = np.random.rand(10)
a

array([0.72864717, 0.36443928, 0.30607028, 0.7336018 , 0.71660245,
       0.62216248, 0.42444182, 0.57517163, 0.15596589, 0.73818104])

In [12]:
a = np.random.randint(1,100,10)
a

array([95, 34,  6, 14, 31, 88, 42, 89, 15, 39])

In [13]:
m = np.random.randint(1,100,(5,5))
m

array([[26,  8, 36, 10, 54],
       [14, 42, 67, 72, 64],
       [22, 63, 56, 94, 60],
       [37, 41,  7, 12, 19],
       [11, 67, 84, 68,  4]])

In [17]:
a = np.linspace(1,10,5, retstep=True)
a

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [18]:
a = np.array('Python')
a

array('Python', dtype='<U6')

In [19]:
a.size

1

In [20]:
l = list('Python')
l

['P', 'y', 't', 'h', 'o', 'n']

In [21]:
a = np.array(list('Python'))
a

array(['P', 'y', 't', 'h', 'o', 'n'], dtype='<U1')

#### Data Type

In [23]:
a = np.array( [1,2,3])
a, a.dtype

(array([1, 2, 3]), dtype('int32'))

### Attributes of ndarray

In [29]:
a = np.full((3,3),3)
print(a.size)
print(a.dtype)
print(a.shape)
print(a.ndim)

9
int32
(3, 3)
2


## Indexing and Slicing

In [32]:
a = np.arange(1,11)

In [33]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
a[0], a[-1]

(1, 10)

In [37]:
a[0:5]

array([1, 2, 3, 4, 5])

In [38]:
a[4:6]

array([5, 6])

In [41]:
a[-1:-4:-1]

array([10,  9,  8])

In [42]:
a[-3:]

array([ 8,  9, 10])

In [44]:
a[:3]

array([1, 2, 3])

In [48]:
a = np.arange(1,26).reshape((5,5))

In [49]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
a[4,3], a[-1,-1]

(24, 25)

In [53]:
a[1,:]

array([ 6,  7,  8,  9, 10])

In [54]:
a[:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [55]:
a[:, -1]

array([ 5, 10, 15, 20, 25])

In [57]:
# last 2 row and 2 cols
a[-2:,-2:]

array([[19, 20],
       [24, 25]])

In [58]:
a[3:,3:]

array([[19, 20],
       [24, 25]])

In [59]:
for n in a:
    print(n)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
[21 22 23 24 25]


# 16-APR-2020

In [2]:
a = np.random.randint(1,100, (5,5))

In [3]:
a

array([[57,  7, 27,  2, 85],
       [ 4,  5, 87, 32, 37],
       [23, 56, 27, 69, 80],
       [11, 29, 90, 35, 85],
       [33, 43, 24, 26, 64]])

In [5]:
count = 0
for row in a:
    for v in row:
      if v % 2 == 0 :
        count +=1
        
print('Count = ', count)        

Count =  9


### Fancy indexing

In [7]:
a = np.random.randint(1,100,10)
a

array([84, 44, 44, 56, 96,  1, 76, 75, 32, 71])

In [9]:
idx = [1,5,7]
a[idx]

array([44,  1, 75])

### Operations on Array

In [10]:
a % 2

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1], dtype=int32)

In [11]:
a + 2

array([86, 46, 46, 58, 98,  3, 78, 77, 34, 73])

In [14]:
b = np.random.randint(1,10,10)
b

array([4, 2, 2, 8, 4, 2, 3, 2, 9, 1])

In [15]:
a + b

array([ 88,  46,  46,  64, 100,   3,  79,  77,  41,  72])

In [16]:
a % 2 == 0

array([ True,  True,  True,  True,  True, False,  True, False,  True,
       False])

In [20]:
print(a)
bidx = a % 2 == 0
print(bidx)
enums = a [bidx]
print(enums, enums.size)

[84 44 44 56 96  1 76 75 32 71]
[ True  True  True  True  True False  True False  True False]
[84 44 44 56 96 76 32] 7


In [21]:
# count no. of even numbers in 5 X 5 array
a = np.random.randint(1,10, (5,5)) 
a % 2 == 0

array([[False,  True,  True,  True,  True],
       [False, False,  True, False, False],
       [ True, False,  True, False,  True],
       [ True, False, False,  True, False],
       [False, False, False, False, False]])

In [23]:
a [a % 2 == 0].size

10

In [24]:
a [a  > 5]

array([6, 8, 7, 6, 7, 8, 9, 9, 7])

In [26]:
a [ (a >= 3) & (a <= 7)]

array([6, 7, 3, 6, 5, 7, 4, 4, 3, 5, 3, 7, 3, 3])

In [28]:
(a % 2 == 0) | (a %  3 == 0)

array([[False,  True,  True,  True,  True],
       [False,  True,  True, False, False],
       [ True, False,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [False,  True, False,  True,  True]])

In [29]:
a

array([[1, 2, 6, 8, 2],
       [7, 3, 6, 5, 7],
       [4, 1, 4, 1, 8],
       [2, 9, 9, 2, 3],
       [5, 3, 7, 3, 3]])

In [30]:
a += 1

In [31]:
a

array([[ 2,  3,  7,  9,  3],
       [ 8,  4,  7,  6,  8],
       [ 5,  2,  5,  2,  9],
       [ 3, 10, 10,  3,  4],
       [ 6,  4,  8,  4,  4]])

### ndarray methods 

In [33]:
a = np.random.randint(1,10,10)
a

array([5, 3, 9, 9, 3, 2, 5, 2, 4, 1])

In [34]:
a.mean()

4.3

In [35]:
a.sum(), a.max(), a.var(), a.std()

(43, 9, 7.010000000000001, 2.6476404589747453)

In [36]:
za = np.zeros(10)
za

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
za.any()

False

In [38]:
za.all()

False

In [39]:
za[0] = 10

In [40]:
za.any(), za.all()

(True, False)

In [42]:
na = np.array([13,11,15,79,1])
(na % 2 == 0).any()

False

In [43]:
na.cumsum()

array([ 13,  24,  39, 118, 119], dtype=int32)

In [45]:
na.sort()
na

array([ 1, 11, 13, 15, 79])

In [47]:
dd = np.random.randint(1,10,(3,3))
dd

array([[7, 5, 8],
       [6, 2, 7],
       [9, 3, 7]])

In [48]:
dd.sum()

54

In [49]:
dd.sum(axis=1)  # 1 means rows, 0 means cols

array([20, 15, 19])

In [50]:
dd.sum(axis=0)

array([22, 10, 22])

### Universal functions

In [53]:
a = np.random.randint(1,10,10)
b = np.random.randint(1,10,10)
a,b

(array([7, 5, 1, 4, 1, 9, 4, 8, 6, 3]), array([2, 8, 7, 7, 1, 6, 9, 9, 1, 5]))

In [54]:
np.divmod(a,b)

(array([3, 0, 0, 0, 1, 1, 0, 0, 6, 0], dtype=int32),
 array([1, 5, 1, 4, 0, 3, 4, 8, 0, 3], dtype=int32))

### copy vs. view

In [3]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = a[:5]
b

array([1, 2, 3, 4, 5])

In [5]:
b[0] = 10

In [6]:
a

array([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [7]:
b[:3] = 100

In [9]:
b,a

(array([100, 100, 100,   4,   5]),
 array([100, 100, 100,   4,   5,   6,   7,   8,   9]))

### Stacking

In [10]:
a = np.arange(4).reshape((2,2))
a

array([[0, 1],
       [2, 3]])

In [11]:
b = np.arange(10,14).reshape((2,2))
b

array([[10, 11],
       [12, 13]])

In [15]:
ab = np.vstack( (a,b))
ab

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [16]:
ab[0,0] = 100

In [17]:
a

array([[0, 1],
       [2, 3]])

### Splitting 

In [21]:
a = np.arange(1,11)

In [24]:
a1, a2 = np.hsplit(a,2)

In [25]:
a1[0] = 100
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [27]:
np.hsplit(a,(2,5))

[array([100,   2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [28]:
np.split(a, (2,5))

[array([100,   2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10])]

### Linear Algebra

In [30]:
a = np.random.randint(1,10,(2,3))
b = np.random.randint(1,10,(3,2))
a,b

(array([[3, 9, 8],
        [5, 7, 6]]),
 array([[8, 6],
        [4, 1],
        [2, 7]]))

In [31]:
a.T

array([[3, 5],
       [9, 7],
       [8, 6]])

In [32]:
a.dot(b)

array([[76, 83],
       [80, 79]])

In [33]:
a @ b

array([[76, 83],
       [80, 79]])

### Reshape

In [42]:
a = np.arange(9)
b = a.reshape(3,3)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
b[0,0] = 100

In [38]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

In [39]:
b.ravel()

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

In [41]:
b.flatten()

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

In [43]:
a = np.arange(10)
a.resize(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
a.ravel('C')    # Row major 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a.ravel('F')    # Col major

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

### Broadcasting 

In [46]:
a = np.arange(5)
a + 10

array([10, 11, 12, 13, 14])